language: csharp
sudo: required
dist: xenial
mono: latest
dotnet: 3.0
before_install:
  - export TRAVIS_REPO_NAME=$(basename $TRAVIS_REPO_SLUG)
  - export SOURCE_BRANCH="master"
script:
  - dotnet build -c Release
  - dotnet test -c Release -f netcoreapp3.0
after_success:
  - bash ./generate-pdf.sh
  - bash ./publish-docs.sh
  - bash ./push-nuget.sh
