name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'
    - name: Where am I?
      run: |
        cd ${{ github.workspace }}
        ls
        cd ..
        ls
        cd ..
        ls
        cd ..
        ls
    - name: Build
      run: dotnet build -c Release ${{ github.workspace }}/Platform.RegularExpressions.Transformer.CSharpToCpp.sln
