name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release -f netcoreapp3.0
    - name: Generate PDF with code
      run: |
        export REPOSITORY_NAME=$(basename ${{ github.repository }})
        export CURRENT_BRANCH=$(basename ${{ github.ref }})
        export DEFAULT_BRANCH="master"
        bash ./generate-pdf.sh
    - name: Publish documentation to gh-pages branch
      run: |
        export REPOSITORY_NAME=$(basename ${{ github.repository }})
        export CURRENT_BRANCH=$(basename ${{ github.ref }})
        export DEFAULT_BRANCH="master"
        export TOKEN="${{ secrets.TOKEN }}"
        bash ./publish-docs.sh
    - name: Publish NuGet package
      run: |
        export REPOSITORY_NAME=$(basename ${{ github.repository }})
        export CURRENT_BRANCH=$(basename ${{ github.ref }})
        export DEFAULT_BRANCH="master"
        export NUGETTOKEN="${{ secrets.NUGETTOKEN }}"
        bash ./push-nuget.sh
    - name: Publish release
      run: |
        export REPOSITORY_NAME=$(basename ${{ github.repository }})
        export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
        export CURRENT_BRANCH=$(basename ${{ github.ref }})
        export DEFAULT_BRANCH="master"
        bash ./publish-release.sh
