name: CI

on: [push, pull_request]

env:
  DEFAULT_BRANCH: master
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TOKEN: ${{ secrets.TOKEN }}
  NUGETTOKEN: ${{ secrets.NUGETTOKEN }}

jobs:
  buildTestAndDeploy:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release -f netcoreapp3.0
    - name: Generate PDF with code
      if: github.event_name == 'push' && endsWith(github.ref, '/master')
      run: |
        export REPOSITORY_NAME=$(basename ${{ github.repository }})
        bash ./generate-pdf.sh
    - name: Publish documentation to gh-pages branch
      if: github.event_name == 'push' && endsWith(github.ref, '/master')
      run: |
        export REPOSITORY_NAME=$(basename ${{ github.repository }})
        bash ./publish-docs.sh
    - name: Publish NuGet package
      if: github.event_name == 'push' && endsWith(github.ref, '/master')
      run: |
        export REPOSITORY_NAME=$(basename ${{ github.repository }})
        bash ./push-nuget.sh
    - name: Publish release
      if: github.event_name == 'push' && endsWith(github.ref, '/master')
      run: |
        export REPOSITORY_NAME=$(basename ${{ github.repository }})
        bash ./publish-release.sh
