name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      DEFAULT_BRANCH: master
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TOKEN: ${{ secrets.TOKEN }}
      NUGETTOKEN: ${{ secrets.NUGETTOKEN }}
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release -f netcoreapp3.0
    - name: Generate PDF with code
      run: |
        export REPOSITORY_NAME=$(basename ${{ github.repository }})
        export CURRENT_BRANCH=$(basename ${{ github.ref }})
        bash ./generate-pdf.sh
    - name: Publish documentation to gh-pages branch
      run: |
        export REPOSITORY_NAME=$(basename ${{ github.repository }})
        export CURRENT_BRANCH=$(basename ${{ github.ref }})
        bash ./publish-docs.sh
    - name: Publish NuGet package
      run: |
        export REPOSITORY_NAME=$(basename ${{ github.repository }})
        export CURRENT_BRANCH=$(basename ${{ github.ref }})
        bash ./push-nuget.sh
    - name: Publish release
      run: |
        export REPOSITORY_NAME=$(basename ${{ github.repository }})
        export CURRENT_BRANCH=$(basename ${{ github.ref }})
        bash ./publish-release.sh
