name: XML

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install xmlstarlet
      run: sudo apt-get install xmlstarlet
    - name: Read data from xml project file
      run: |
        export REPOSITORY_NAME=$(basename ${{ github.repository }})
        echo $REPOSITORY_NAME
        export PACKAGE_VERSION=$(xmlstarlet sel -t -m '//VersionPrefix[1]' -v . -n <Platform.$REPOSITORY_NAME/Platform.$REPOSITORY_NAME.csproj)
        echo $PACKAGE_VERSION
        export PACKAGE_RELEASE_NOTES=$(xmlstarlet sel -t -m '//PackageReleaseNotes[1]' -v . -n <Platform.$REPOSITORY_NAME/Platform.$REPOSITORY_NAME.csproj)
        echo $PACKAGE_RELEASE_NOTES
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/releases \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "tag_name": "${PACKAGE_VERSION}",
          "target_commitish": "master",
          "name": "${PACKAGE_VERSION}",
          "body": "${PACKAGE_RELEASE_NOTES}",
          "draft": false,
          "prerelease": false
          }'
