name: XML

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install xmlstarlet
      run: sudo apt-get install xmlstarlet
    - name: What is the repository name?
      run: |
        export REPOSITORY_NAME=$(echo "${${{ github.repository }}#*/}" | sed 's/.*/\u&/')
        echo $REPOSITORY_NAME
