name: XML

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install xmlstarlet
      run: sudo apt-get install xmlstarlet
    - name: What is the repository name?
      run: |
        export REPOSITORY_NAME=$(basename ${{ github.repository }})
        echo $REPOSITORY_NAME
    - name: Reading from xml
      run: xmlstarlet sel -t -m '//VersionPrefix[1]' -v . -n <Platform.$REPOSITORY_NAME/Platform.$REPOSITORY_NAME.csproj
